<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            ['country_code' => 'AF', 'country_name' => 'Afghanistan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AX', 'country_name' => 'Aland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AL', 'country_name' => 'Albanië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'DZ', 'country_name' => 'Algerije', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'VI', 'country_name' => 'Amerikaanse Maagdeneilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AS', 'country_name' => 'Amerikaans-Samoa', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AD', 'country_name' => 'Andorra', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AO', 'country_name' => 'Angola', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AI', 'country_name' => 'Anguilla', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AQ', 'country_name' => 'Antarctica', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AG', 'country_name' => 'Antigua en Barbuda', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AR', 'country_name' => 'Argentinië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AM', 'country_name' => 'Armenië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AW', 'country_name' => 'Aruba', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AU', 'country_name' => 'Australië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AZ', 'country_name' => 'Azerbeidzjan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BS', 'country_name' => 'Bahama\'s', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BH', 'country_name' => 'Bahrein', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BD', 'country_name' => 'Bangladesh', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BB', 'country_name' => 'Barbados', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BE', 'country_name' => 'België', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BZ', 'country_name' => 'Belize', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BJ', 'country_name' => 'Benin', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BM', 'country_name' => 'Bermuda', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BT', 'country_name' => 'Bhutan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BO', 'country_name' => 'Bolivia', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BQ', 'country_name' => 'Bonaire, Sint Eustatius en Saba', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BA', 'country_name' => 'Bosnië en Herzegovina', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BW', 'country_name' => 'Botswana', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BV', 'country_name' => 'Bouveteiland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BR', 'country_name' => 'Brazilië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'VG', 'country_name' => 'Britse Maagdeneilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'IO', 'country_name' => 'Brits Indische Oceaanterritorium', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BN', 'country_name' => 'Brunei', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BG', 'country_name' => 'Bulgarije', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BF', 'country_name' => 'Burkina Faso', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BI', 'country_name' => 'Burundi', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KH', 'country_name' => 'Cambodja', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CF', 'country_name' => 'Centraal-Afrikaanse Republiek', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CL', 'country_name' => 'Chili', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CN', 'country_name' => 'China', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CX', 'country_name' => 'Christmaseiland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CC', 'country_name' => 'Cocoseilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CO', 'country_name' => 'Colombia', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KM', 'country_name' => 'Comoren', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CG', 'country_name' => 'Congo-Brazzaville', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CD', 'country_name' => 'Congo-Kinshasa', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CK', 'country_name' => 'Cookeilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CR', 'country_name' => 'Costa Rica', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CU', 'country_name' => 'Cuba', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CW', 'country_name' => 'Curaçao', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CY', 'country_name' => 'Cyprus', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'DK', 'country_name' => 'Denemarken', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'DJ', 'country_name' => 'Djibouti', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'DM', 'country_name' => 'Dominica', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'DO', 'country_name' => 'Dominicaanse Republiek', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'DE', 'country_name' => 'Duitsland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'EC', 'country_name' => 'Ecuador', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'EG', 'country_name' => 'Egypte', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SV', 'country_name' => 'El Salvador', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GQ', 'country_name' => 'Equatoriaal-Guinea', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'ER', 'country_name' => 'Eritrea', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'EE', 'country_name' => 'Estland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'ET', 'country_name' => 'Ethiopië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'FO', 'country_name' => 'Faeröer', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'FK', 'country_name' => 'Falklandeilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'FJ', 'country_name' => 'Fiji', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PH', 'country_name' => 'Filipijnen', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'FI', 'country_name' => 'Finland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'FR', 'country_name' => 'Frankrijk', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TF', 'country_name' => 'Franse Zuidelijke en Antarctische Gebieden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GF', 'country_name' => 'Frans-Guyana', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PF', 'country_name' => 'Frans-Polynesië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GA', 'country_name' => 'Gabon', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GM', 'country_name' => 'Gambia', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GE', 'country_name' => 'Georgië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GH', 'country_name' => 'Ghana', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GI', 'country_name' => 'Gibraltar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GD', 'country_name' => 'Grenada', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GR', 'country_name' => 'Griekenland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GL', 'country_name' => 'Groenland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GP', 'country_name' => 'Guadeloupe', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GU', 'country_name' => 'Guam', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GT', 'country_name' => 'Guatemala', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GG', 'country_name' => 'Guernsey', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GN', 'country_name' => 'Guinee', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GW', 'country_name' => 'Guinee-Bissau', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GY', 'country_name' => 'Guyana', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'HT', 'country_name' => 'Haïti', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'HM', 'country_name' => 'Heard en McDonaldeilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'HN', 'country_name' => 'Honduras', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'HU', 'country_name' => 'Hongarije', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'HK', 'country_name' => 'Hongkong', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'IE', 'country_name' => 'Ierland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'IS', 'country_name' => 'IJsland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'IN', 'country_name' => 'India', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'ID', 'country_name' => 'Indonesië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'IQ', 'country_name' => 'Irak', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'IR', 'country_name' => 'Iran', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'IL', 'country_name' => 'Israël', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'IT', 'country_name' => 'Italië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CI', 'country_name' => 'Ivoorkust', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'JM', 'country_name' => 'Jamaica', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'JP', 'country_name' => 'Japan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'YE', 'country_name' => 'Jemen', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'JE', 'country_name' => 'Jersey', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'JO', 'country_name' => 'Jordanië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KY', 'country_name' => 'Kaaimaneilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CV', 'country_name' => 'Kaapverdië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CM', 'country_name' => 'Kameroen', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KZ', 'country_name' => 'Kazachstan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KE', 'country_name' => 'Kenia', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KG', 'country_name' => 'Kirgizië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KI', 'country_name' => 'Kiribati', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'UM', 'country_name' => 'Kleine afgelegen eilanden van de Verenigde Staten', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KW', 'country_name' => 'Koeweit', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'HR', 'country_name' => 'Kroatië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LA', 'country_name' => 'Laos', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LS', 'country_name' => 'Lesotho', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LV', 'country_name' => 'Letland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LB', 'country_name' => 'Libanon', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LR', 'country_name' => 'Liberia', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LY', 'country_name' => 'Libië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LI', 'country_name' => 'Liechtenstein', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LT', 'country_name' => 'Litouwen', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LU', 'country_name' => 'Luxemburg', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MO', 'country_name' => 'Macau', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MK', 'country_name' => 'Macedonië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MG', 'country_name' => 'Madagaskar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MW', 'country_name' => 'Malawi', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MV', 'country_name' => 'Maladiven', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MY', 'country_name' => 'Maleisië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'ML', 'country_name' => 'Mali', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MT', 'country_name' => 'Malta', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'IM', 'country_name' => 'Man', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MA', 'country_name' => 'Marokko', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MH', 'country_name' => 'Marshalleilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MQ', 'country_name' => 'Martinique', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MR', 'country_name' => 'Mauritanië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MU', 'country_name' => 'Mauritius', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'YT', 'country_name' => 'Mayotte', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'FM', 'country_name' => 'Micronesia', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MD', 'country_name' => 'Moldavië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MC', 'country_name' => 'Monaco', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MN', 'country_name' => 'Mongolië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'ME', 'country_name' => 'Montenegro', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MS', 'country_name' => 'Montserrat', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MZ', 'country_name' => 'Mozambique', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MM', 'country_name' => 'Myanmar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NA', 'country_name' => 'Namibië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NR', 'country_name' => 'Nauru', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NL', 'country_name' => 'Nederland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NP', 'country_name' => 'Nepal', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NI', 'country_name' => 'Nicaragua', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NC', 'country_name' => 'Nieuw-Caledonië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NZ', 'country_name' => 'Nieuw-Zeeland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NE', 'country_name' => 'Niger', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NG', 'country_name' => 'Nigeria', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NU', 'country_name' => 'Niue', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MP', 'country_name' => 'Noordelijke Marianen', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KP', 'country_name' => 'Noord-Korea', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NO', 'country_name' => 'Noorwegen', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'NF', 'country_name' => 'Norfolk', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'UG', 'country_name' => 'Oeganda', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'UA', 'country_name' => 'Oekraïne', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'UZ', 'country_name' => 'Oezbekistan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'OM', 'country_name' => 'Oman', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AT', 'country_name' => 'Oostenrijk', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TL', 'country_name' => 'Oost-Timor', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PK', 'country_name' => 'Pakistan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PW', 'country_name' => 'Palau', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PS', 'country_name' => 'Palestina', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PA', 'country_name' => 'Panama', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PG', 'country_name' => 'Papoea-Nieuw-Guinea', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PY', 'country_name' => 'Paraguay', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PE', 'country_name' => 'Peru', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PN', 'country_name' => 'Pitcairneilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PL', 'country_name' => 'Polen', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PT', 'country_name' => 'Portugal', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PR', 'country_name' => 'Puerto Rico', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'QA', 'country_name' => 'Qatar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'RE', 'country_name' => 'Réunion', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'RO', 'country_name' => 'Roemenië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'RU', 'country_name' => 'Rusland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'RW', 'country_name' => 'Rwanda', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BL', 'country_name' => 'Saint-Barthélemy', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KN', 'country_name' => 'Saint Kitts en Nevis', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LC', 'country_name' => 'Saint Lucia', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'PM', 'country_name' => 'Saint-Pierre en Miquelon', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'VC', 'country_name' => 'Saint Vincent en de Grenadines', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SB', 'country_name' => 'Salomonseilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'WS', 'country_name' => 'Samoa', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SM', 'country_name' => 'San Marino', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SA', 'country_name' => 'Saoedi-Arabië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'ST', 'country_name' => 'Sao Tomé en Principe', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SN', 'country_name' => 'Senegal', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'RS', 'country_name' => 'Servië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SC', 'country_name' => 'Seychellen', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SL', 'country_name' => 'Sierra Leone', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SG', 'country_name' => 'Singapore', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SH', 'country_name' => 'Sint-Helena, Ascension en Tristan da Cunha', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'MF', 'country_name' => 'Sint-Maarten', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SI', 'country_name' => 'Slovenië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SK', 'country_name' => 'Slowakije', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SD', 'country_name' => 'Soedan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SO', 'country_name' => 'Somalië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'ES', 'country_name' => 'Spanje', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SJ', 'country_name' => 'Spitsbergen en Jan Mayen', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'LK', 'country_name' => 'Sri Lanka', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SR', 'country_name' => 'Suricountry_name', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SZ', 'country_name' => 'Swaziland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SY', 'country_name' => 'Syrië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TJ', 'country_name' => 'Tadzjikistan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TW', 'country_name' => 'Taiwan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TZ', 'country_name' => 'Tanzania', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TH', 'country_name' => 'Thailand', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TG', 'country_name' => 'Togo', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TK', 'country_name' => 'Tokelau', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TO', 'country_name' => 'Tonga', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TT', 'country_name' => 'Trinidad en Tobago', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TD', 'country_name' => 'Tsjaad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CZ', 'country_name' => 'Tsjechië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TN', 'country_name' => 'Tunesië', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TR', 'country_name' => 'Turkije', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TM', 'country_name' => 'Turkmenistan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TC', 'country_name' => 'Turks- en Caicoseilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'TV', 'country_name' => 'Tuvalu', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'UY', 'country_name' => 'Uruguay', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'VU', 'country_name' => 'Vanuatu', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'VA', 'country_name' => 'Vaticaanstad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'VE', 'country_name' => 'Venezuela', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'AE', 'country_name' => 'Verenigde Arabische Emiraten', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'US', 'country_name' => 'Verenigde Staten', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GB', 'country_name' => 'Verenigd Koninkrijk', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'VN', 'country_name' => 'Vietnam', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'WF', 'country_name' => 'Wallis en Futuna', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'EH', 'country_name' => 'Westelijke Sahara', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'BY', 'country_name' => 'Wit-Rusland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'ZM', 'country_name' => 'Zambia', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'ZW', 'country_name' => 'Zimbabwe', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'ZA', 'country_name' => 'Zuid-Afrika', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'GS', 'country_name' => 'Zuid-Georgia en de Zuidelijke Sandwicheilanden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'KR', 'country_name' => 'Zuid-Korea', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SS', 'country_name' => 'Zuid-Soedan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'SE', 'country_name' => 'Zweden', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['country_code' => 'CH', 'country_name' => 'Zwitserland', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
        ]);
    }
}
