<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CurrenciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('currencies')->insert([
            ['currency_iso_code' =>'AFN' , 'currency_name' => 'Afghani', 'currency_symbol' => '؋' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'ALL' , 'currency_name' => 'Lek', 'currency_symbol' => 'Lek' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'ANG' , 'currency_name' => 'Netherlands Antillian Guilder', 'currency_symbol' => 'ƒ' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'ARS' , 'currency_name' => 'Argentine Peso', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'AUD' , 'currency_name' => 'Australian Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'AWG' , 'currency_name' => 'Aruban Guilder', 'currency_symbol' => 'ƒ' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'AZN' , 'currency_name' => 'Azerbaijanian Manat', 'currency_symbol' => 'ман' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BAM' , 'currency_name' => 'Convertible Marks', 'currency_symbol' => 'KM' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' => 'BDT', 'currency_name' => 'Bangladeshi Taka', 'currency_symbol' => '৳', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BBD' , 'currency_name' => 'Barbados Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BGN' , 'currency_name' => 'Bulgarian Lev', 'currency_symbol' => 'лв' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BMD' , 'currency_name' => 'Bermudian Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BND' , 'currency_name' => 'Brunei Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BOB' , 'currency_name' => 'BOV Boliviano Mvdol', 'currency_symbol' => '$b' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BRL' , 'currency_name' => 'Brazilian Real', 'currency_symbol' => 'R$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BSD' , 'currency_name' => 'Bahamian Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BWP' , 'currency_name' => 'Pula', 'currency_symbol' => 'P' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BYR' , 'currency_name' => 'Belarussian Ruble', 'currency_symbol' => '₽' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'BZD' , 'currency_name' => 'Belize Dollar', 'currency_symbol' => 'BZ$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'CAD' , 'currency_name' => 'Canadian Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'CHF' , 'currency_name' => 'Swiss Franc', 'currency_symbol' => 'CHF' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'CLP' , 'currency_name' => 'CLF Chilean Peso Unidades de fomento', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'CNY' , 'currency_name' => 'Yuan Renminbi', 'currency_symbol' => '¥' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'COP' , 'currency_name' => 'COU Colombian Peso Unidad de Valor Real', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'CRC' , 'currency_name' => 'Costa Rican Colon', 'currency_symbol' => '₡' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'CUP' , 'currency_name' => 'CUC Cuban Peso Peso Convertible', 'currency_symbol' => '₱' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'CZK' , 'currency_name' => 'Czech Koruna', 'currency_symbol' => 'Kč' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'DKK' , 'currency_name' => 'Danish Krone', 'currency_symbol' => 'kr' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'DOP' , 'currency_name' => 'Dominican Peso', 'currency_symbol' => 'RD$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'EGP' , 'currency_name' => 'Egyptian Pound', 'currency_symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'EUR' , 'currency_name' => 'Euro', 'currency_symbol' => '€' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'FJD' , 'currency_name' => 'Fiji Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'FKP' , 'currency_name' => 'Falkland Islands Pound', 'currency_symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'GBP' , 'currency_name' => 'Pound Sterling', 'currency_symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'GIP' , 'currency_name' => 'Gibraltar Pound', 'currency_symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'GTQ' , 'currency_name' => 'Quetzal', 'currency_symbol' => 'Q' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'GYD' , 'currency_name' => 'Guyana Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'HKD' , 'currency_name' => 'Hong Kong Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'HNL' , 'currency_name' => 'Lempira', 'currency_symbol' => 'L' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'HRK' , 'currency_name' => 'Croatian Kuna', 'currency_symbol' => 'kn' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'HUF' , 'currency_name' => 'Forint', 'currency_symbol' => 'Ft' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'IDR' , 'currency_name' => 'Rupiah', 'currency_symbol' => 'Rp' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'ILS' , 'currency_name' => 'New Israeli Sheqel', 'currency_symbol' => '₪' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'IRR' , 'currency_name' => 'Iranian Rial', 'currency_symbol' => '﷼' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'ISK' , 'currency_name' => 'Iceland Krona', 'currency_symbol' => 'kr' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'JMD' , 'currency_name' => 'Jamaican Dollar', 'currency_symbol' => 'J$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'JPY' , 'currency_name' => 'Yen', 'currency_symbol' => '¥' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'KGS' , 'currency_name' => 'Som', 'currency_symbol' => 'лв' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'KHR' , 'currency_name' => 'Riel', 'currency_symbol' => '៛' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'KPW' , 'currency_name' => 'North Korean Won', 'currency_symbol' => '₩' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'KRW' , 'currency_name' => 'Won', 'currency_symbol' => '₩' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'KYD' , 'currency_name' => 'Cayman Islands Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'KZT' , 'currency_name' => 'Tenge', 'currency_symbol' => 'лв' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'LAK' , 'currency_name' => 'Kip', 'currency_symbol' => '₭' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'LBP' , 'currency_name' => 'Lebanese Pound', 'currency_symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'LKR' , 'currency_name' => 'Sri Lanka Rupee', 'currency_symbol' => '₨' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'LRD' , 'currency_name' => 'Liberian Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'LTL' , 'currency_name' => 'Lithuanian Litas', 'currency_symbol' => 'Lt' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'LVL' , 'currency_name' => 'Latvian Lats', 'currency_symbol' => 'Ls' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'MKD' , 'currency_name' => 'Denar', 'currency_symbol' => 'ден' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'MNT' , 'currency_name' => 'Tugrik', 'currency_symbol' => '₮' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'MUR' , 'currency_name' => 'Mauritius Rupee', 'currency_symbol' => '₨' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'MXN' , 'currency_name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI]', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'MYR' , 'currency_name' => 'Malaysian Ringgit', 'currency_symbol' => 'RM' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'MZN' , 'currency_name' => 'Metical', 'currency_symbol' => 'MT' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'NGN' , 'currency_name' => 'Naira', 'currency_symbol' => '₦' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'NIO' , 'currency_name' => 'Cordoba Oro', 'currency_symbol' => 'C$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'NOK' , 'currency_name' => 'Norwegian Krone', 'currency_symbol' => 'kr' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'NPR' , 'currency_name' => 'Nepalese Rupee', 'currency_symbol' => '₨' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'NZD' , 'currency_name' => 'New Zealand Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'OMR' , 'currency_name' => 'Rial Omani', 'currency_symbol' => '﷼' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'PAB' , 'currency_name' => 'USD Balboa US Dollar', 'currency_symbol' => 'B/.' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'PEN' , 'currency_name' => 'Nuevo Sol', 'currency_symbol' => 'S/.' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'PHP' , 'currency_name' => 'Philippine Peso', 'currency_symbol' => 'Php' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'PKR' , 'currency_name' => 'Pakistan Rupee', 'currency_symbol' => '₨' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'PLN' , 'currency_name' => 'Zloty', 'currency_symbol' => 'zł' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'PYG' , 'currency_name' => 'Guarani', 'currency_symbol' => 'Gs' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'QAR' , 'currency_name' => 'Qatari Rial', 'currency_symbol' => '﷼' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'RON' , 'currency_name' => 'New Leu', 'currency_symbol' => 'lei' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'RSD' , 'currency_name' => 'Serbian Dinar', 'currency_symbol' => 'Дин.' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'RUB' , 'currency_name' => 'Russian Ruble', 'currency_symbol' => 'руб' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'SAR' , 'currency_name' => 'Saudi Riyal', 'currency_symbol' => '﷼' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'SBD' , 'currency_name' => 'Solomon Islands Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'SCR' , 'currency_name' => 'Seychelles Rupee', 'currency_symbol' => '₨' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'SEK' , 'currency_name' => 'Swedish Krona', 'currency_symbol' => 'kr' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'SGD' , 'currency_name' => 'Singapore Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'SHP' , 'currency_name' => 'Saint Helena Pound', 'currency_symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'SOS' , 'currency_name' => 'Somali Shilling', 'currency_symbol' => 'S' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'SRD' , 'currency_name' => 'Surinam Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'SVC' , 'currency_name' => 'USD El Salvador Colon US Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'SYP' , 'currency_name' => 'Syrian Pound', 'currency_symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'THB' , 'currency_name' => 'Baht', 'currency_symbol' => '฿' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'TRY' , 'currency_name' => 'Turkish Lira', 'currency_symbol' => 'TL' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'TTD' , 'currency_name' => 'Trinidad and Tobago Dollar', 'currency_symbol' => 'TT$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'TWD' , 'currency_name' => 'New Taiwan Dollar', 'currency_symbol' => 'NT$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'UAH' , 'currency_name' => 'Hryvnia', 'currency_symbol' => '₴' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'USD' , 'currency_name' => 'US Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'UYU' , 'currency_name' => 'UYI Uruguay Peso en Unidades Indexadas', 'currency_symbol' => '$U' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'UZS' , 'currency_name' => 'Uzbekistan Sum', 'currency_symbol' => 'лв' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'VEF' , 'currency_name' => 'Bolivar Fuerte', 'currency_symbol' => 'Bs' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'VND' , 'currency_name' => 'Dong', 'currency_symbol' => '₫' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'XCD' , 'currency_name' => 'East Caribbean Dollar', 'currency_symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'YER' , 'currency_name' => 'Yemeni Rial', 'currency_symbol' => '﷼' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['currency_iso_code' =>'ZAR' , 'currency_name' => 'Rand', 'currency_symbol' => 'R' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
        ]);
    }
}
